"""modificacion de tablas y nuevas tablas

Revision ID: dcca1b1716a0
Revises: 96f6ca041876
Create Date: 2026-02-24 07:22:44.871678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision: str = 'dcca1b1716a0'
down_revision: Union[str, Sequence[str], None] = '96f6ca041876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('sucursal', sa.String(length=100), nullable=False),
    sa.Column('aspirante', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('users', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'uuid')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_deleted')
    op.drop_table('applications')
    # ### end Alembic commands ###
